[package]
name = "gc"
version = "0.1.0"
authors = ["Samuel Lampa <samuel.lampa@rilnet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "0.2.15"
